Create marker interface for entities
Fixes following error:
  System.InvalidOperationException: The entity type 'List<TestCase>' was not found. Ensure that the entity type has been added to the model.
     at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
     at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
     at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
     at SG.TestRunService.Data.Services.Implementations.BaseDbService.InsertAsync[TEntity](TEntity entity) in D:\Projects\SG\TestRunService\SG.TestRunService\Data\Services\Implementations\BaseDbService.cs:line 88
     at SG.TestRunService.ServiceImplementations.TestCaseService.InsertAsync(IEnumerable`1 testCaseRequests) in D:\Projects\SG\TestRunService\SG.TestRunService\ServiceImplementations\TestCaseService.cs:line 32
     at SG.TestRunService.Controllers.TestCasesController.Insert() in D:\Projects\SG\TestRunService\SG.TestRunService\Controllers\TestCasesController.cs:line 77"

To help compiler find the correct overload for `IBaseDbService.InsertAsync` when the parameter is `IEnumerable<TestCase>`, we need at least a marker interface.